/*  Inconnuclear: A Dungeon-Diving RPG
Copyleft (C) 2024-present RetroPipes
Licensed under MIT. See the LICENSE file for details.

All support is handled via the GitHub repository: https://github.com/retropipes/inconnuclear
 */
package org.retropipes.inconnuclear.loader.image.gameobject;

import java.net.URL;

import org.retropipes.diane.asset.image.DianeImageIndex;
import org.retropipes.diane.objectmodel.ObjectId;
import org.retropipes.inconnuclear.locale.FileExtension;
import org.retropipes.inconnuclear.locale.Strings;
import org.retropipes.inconnuclear.locale.Untranslated;

public enum ObjectImageId implements DianeImageIndex, ObjectId {
    EMPTY, WALL, DARKNESS, BOUNDS, PARTY, NOTE, NOTHING, EASY_MONSTER, NORMAL_MONSTER, HARD_MONSTER, TILE, ARMOR_SHOP,
    BANK, HEALER, ITEM_SHOP, SPELL_SHOP, SURGE_SHOP, WEAPON_SHOP, STAIRS_DOWN, STAIRS_UP, GRASS, TREE, CUT_TREE, AXE,
    DIRT, WATER, DEEP_WATER, DEEPER_WATER, DEEPEST_WATER, BOOTS, FORCE_FIELD, ENERGY_SPHERE, PUSHABLE_BLOCK, ICE,
    SUNKEN_BLOCK, LAVA, SPRING, PIT, BOMB, BOMB_FUSE_1, BOMB_FUSE_2, BOMB_FUSE_3, BOMB_FUSE_4, BOOM, MISSILE_NORTH,
    MISSILE_EAST, MISSILE_WEST, MISSILE_SOUTH, COUNTERPOISON_AMULET, POISONOUS_AMULET, CREATION_WAND, DESTRUCTION_WAND,
    DISARM_TRAP_WAND, REMOTE_ACTION_WAND, LIGHT_WAND, FINISH_MAKING_WAND, ROTATION_WAND, DEATH_WAND, TELEPORT_SELF_WAND,
    TELEPORT_OBJECT_DOWN_WAND, TELEPORT_OBJECT_UP_WAND, TELEPORT_OBJECT_RANDOMLY_WAN, CLOCKWISE_ROTATE_SELF_TRAP,
    COUNTERCLOCKWISE_ROTATE_SELF_TRAP, CONFUSION_TRAP, DIZZY_TRAP, DRUNK_TRAP, U_TURN_TRAP, HURT_TRAP,
    VARIABLE_HURT_TRAP, HEAL_TRAP, VARIABLE_HEAL_TRAP, DRAIN_TRAP, VARIABLE_DRAIN_TRAP, SURGE_TRAP, VARIABLE_SURGE_TRAP,
    CLOCKWISE_ROTATE_LEVEL_TRAP, COUNTERCLOCKWISE_ROTATE_LEVEL_TRAP, WALL_TRAP, LIGHT_TRAP, DARKNESS_TRAP, WARP_TRAP,
    EXPLORE_ON_TRAP, EXPLORE_OFF_TRAP, LINE_OF_SIGHT_ON_TRAP, LINE_OF_SIGHT_OFF_TRAP, RED_BUTTON, RED_OFF_WALL,
    RED_ON_WALL, RED_KEY, RED_LOCK, RED_CRYSTAL, RED_CRYSTAL_WALL, RED_ALL_BUTTON, RED_ALL_DOOR, RED_PRESSURE_BUTTON,
    RED_PRESSURE_DOOR, RED_TRIGGER_BUTTON, RED_TRIGGER_DOOR, YELLOW_BUTTON, YELLOW_OFF_WALL, YELLOW_ON_WALL, YELLOW_KEY,
    YELLOW_LOCK, YELLOW_CRYSTAL, YELLOW_CRYSTAL_WALL, YELLOW_ALL_BUTTON, YELLOW_ALL_DOOR, YELLOW_PRESSURE_BUTTON,
    YELLOW_PRESSURE_DOOR, YELLOW_TRIGGER_BUTTON, YELLOW_TRIGGER_DOOR, GREEN_BUTTON, GREEN_OFF_WALL, GREEN_ON_WALL,
    GREEN_KEY, GREEN_LOCK, GREEN_CRYSTAL, GREEN_CRYSTAL_WALL, GREEN_ALL_BUTTON, GREEN_ALL_DOOR, GREEN_PRESSURE_BUTTON,
    GREEN_PRESSURE_DOOR, GREEN_TRIGGER_BUTTON, GREEN_TRIGGER_DOOR, BLUE_BUTTON, BLUE_OFF_WALL, BLUE_ON_WALL, BLUE_KEY,
    BLUE_LOCK, BLUE_CRYSTAL, BLUE_CRYSTAL_WALL, BLUE_ALL_BUTTON, BLUE_ALL_DOOR, BLUE_PRESSURE_BUTTON,
    BLUE_PRESSURE_DOOR, BLUE_TRIGGER_BUTTON, BLUE_TRIGGER_DOOR, MAGENTA_BUTTON, MAGENTA_OFF_WALL, MAGENTA_ON_WALL,
    MAGENTA_KEY, MAGENTA_LOCK, MAGENTA_CRYSTAL, MAGENTA_CRYSTAL_WALL, MAGENTA_ALL_BUTTON, MAGENTA_ALL_DOOR,
    MAGENTA_PRESSURE_BUTTON, MAGENTA_PRESSURE_DOOR, MAGENTA_TRIGGER_BUTTON, MAGENTA_TRIGGER_DOOR, CYAN_BUTTON,
    CYAN_OFF_WALL, CYAN_ON_WALL, CYAN_KEY, CYAN_LOCK, CYAN_CRYSTAL, CYAN_CRYSTAL_WALL, CYAN_ALL_BUTTON, CYAN_ALL_DOOR,
    CYAN_PRESSURE_BUTTON, CYAN_PRESSURE_DOOR, CYAN_TRIGGER_BUTTON, CYAN_TRIGGER_DOOR, ORANGE_BUTTON, ORANGE_OFF_WALL,
    ORANGE_ON_WALL, ORANGE_KEY, ORANGE_LOCK, ORANGE_CRYSTAL, ORANGE_CRYSTAL_WALL, ORANGE_ALL_BUTTON, ORANGE_ALL_DOOR,
    ORANGE_PRESSURE_BUTTON, ORANGE_PRESSURE_DOOR, ORANGE_TRIGGER_BUTTON, ORANGE_TRIGGER_DOOR, PURPLE_BUTTON,
    PURPLE_OFF_WALL, PURPLE_ON_WALL, PURPLE_KEY, PURPLE_LOCK, PURPLE_CRYSTAL, PURPLE_CRYSTAL_WALL, PURPLE_ALL_BUTTON,
    PURPLE_ALL_DOOR, PURPLE_PRESSURE_BUTTON, PURPLE_PRESSURE_DOOR, PURPLE_TRIGGER_BUTTON, PURPLE_TRIGGER_DOOR,
    MINOR_HEAL_POTION, MINOR_HURT_POTION, MINOR_SURGE_POTION, MINOR_DRAIN_POTION, MINOR_RANDOM_POTION,
    MINOR_UNKNOWN_POTION, MAJOR_HEAL_POTION, MAJOR_HURT_POTION, MAJOR_SURGE_POTION, MAJOR_DRAIN_POTION,
    MAJOR_RANDOM_POTION, MAJOR_UNKNOWN_POTION, SUPER_HEAL_POTION, SUPER_HURT_POTION, SUPER_SURGE_POTION,
    SUPER_DRAIN_POTION, SUPER_RANDOM_POTION, SUPER_UNKNOWN_POTION, CLOSED_DOOR, OPEN_DOOR, MOVING_BLOCK, COPY_BLOCK,
    FINISH, FINISH_TO, FAKE_FINISH, MOVING_FINISH, SEALED_FINISH, SEALING_WALL, SIGN, PILLAR, TELEPORT,
    CONTROLLABLE_TELEPORT, CHAIN_TELEPORT, N_WAY_TELEPORT, RANDOM_TELEPORT, ONE_SHOT_TELEPORT, TWO_WAY_TELEPORT,
    CONDITIONAL_TELEPORT, CONTROLLABLE_ONE_SHOT_TELEPORT, CHAIN_ONE_SHOT_TELEPORT, N_WAY_ONE_SHOT_TELEPORT,
    RANDOM_ONE_SHOT_TELEPORT, CONDITIONAL_ONE_SHOT_TELEPORT, CONDITIONAL_CHAIN_TELEPORT, BLOCK_TELEPORT, TEN_MISSILES,
    KEY, TREASURE_CHEST, TABLET, TABLET_SLOT, SINGLE_HOURGLASS, DOUBLE_HOURGLASS, TRIPLE_HOURGLASS, QUAD_HOURGLASS,
    HALF_HOURGLASS, THIRD_HOURGLASS, FOURTH_HOURGLASS, PULLABLE_BLOCK, PUSH_POWER, PULL_POWER, TUNNEL, _CREATURE, _NONE;

    @Override
    public String getName() {
	if (this == ObjectImageId._NONE || this == ObjectImageId._CREATURE) {
	    return null;
	}
	return Integer.toString(this.ordinal());
    }

    @Override
    public URL getURL() {
	if (this == ObjectImageId._NONE || this == ObjectImageId._CREATURE) {
	    return null;
	}
	return this.getClass().getResource(Strings.untranslated(Untranslated.OBJECT_IMAGE_LOAD_PATH) + this.getName()
		+ Strings.fileExtension(FileExtension.IMAGE));
    }
}
